/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CidadeController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Cidade;
import tools.CaixaDeDialogo;
import tools.Combos;

/**
 *
 * @author jdhein
 */
public class TelaCidades extends javax.swing.JFrame {

    Combos comboEstados;
    /**
     * Creates new form TelaCidades
     */
    public TelaCidades() {
        initComponents();
        
        try {
            
            comboEstados = new Combos(jcbEstados);
            comboEstados.preencheCombo(" SELECT id, nome FROM estados ORDER BY nome ");
        
        } catch (SQLException ex) {
            Logger.getLogger(TelaCidades.class.getName()).log(Level.SEVERE, null, ex);
            CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(), 'e');
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbEstados = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        chbEstoque = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 81, -1, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 103, 158, -1));

        txtId.setText("ID");
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 32, -1, -1));

        jLabel2.setText("Estado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 143, -1, -1));

        jcbEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 165, 158, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        btnLimpar.setText("Limpar");
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        chbEstoque.setText("Controla Estoque");
        chbEstoque.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbEstoqueStateChanged(evt);
            }
        });
        getContentPane().add(chbEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("SIM");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("NÃO");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try{
            if(validarDados() == true){
                Cidade objeto = guardarDados();
                if(objeto != null){
                
                    CidadeController controller = new CidadeController();
                    String ret = controller.incluir(objeto);
                    if(ret.equals("")){
                        CaixaDeDialogo.obterinstancia().exibirMensagem("Sucesso", 'i');
                    }else{
                        CaixaDeDialogo.obterinstancia().exibirMensagem(ret, 'e');
                    }                
                }
                
            }            
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void chbEstoqueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbEstoqueStateChanged
        if(chbEstoque.isSelected()){
            txtNome.setText("");
            txtNome.setEnabled(false);
        }else{
            txtNome.setEnabled(true);
        }
    }//GEN-LAST:event_chbEstoqueStateChanged

    private Cidade guardarDados(){
        try{
            Cidade objeto = new Cidade();
            
            Combos estado = (Combos) jcbEstados.getSelectedItem();
            int idEstado = Integer.parseInt(estado.getCodigo());
            
            objeto.setNome(txtNome.getText());
            objeto.setId_estado(idEstado);
            
            return objeto;            
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(), 'e');
            return null;
        }
    }
    
    //retornou TRUE = validação com sucesso
    private boolean validarDados(){
        try{
            
            if(txtNome.getText().trim().equals("")){
               CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um nome");
               return false;
            }
            
            if(jcbEstados.getSelectedIndex() <= 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um estado");
                return false;
            }
            
            return true;
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage(), 'e');
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JComboBox<String> jcbEstados;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
